### ISSUE TITLE
react-native run-android 出錯

### ISSUE THREAD

**Issue by ambilo** [syun0216/goforeat#26]
你好，谢谢你开源了这个项目。想请教在开发环境下启动这个应用程式的正确步骤是怎样。
我依照一般react native的应用执行react-native run-android後便出现以下error，上网找过不同的解决方案仍解决不了。

```
Starting: Intent { cmp=com.goforeat_app/.MainActivity }
Error type 3
Error: Activity class {com.goforeat_app/com.goforeat_app.MainActivity} does not exist.
```

**Comment by syun0216** [comment]
看一下这个启动教程，看可不可以https://github.com/syun0216/goforeat/blob/master/more/%E5%90%AF%E5%8A%A8%E9%A1%B9%E7%9B%AE.md

**Comment by ambilo** [comment]
谢谢你写了这个启动教程，非常实用。
可是我还卡在这个问题上，没有成功把项目建立起来，让我再试试在其他环境下执行後回来报告。
